// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBD7GcIQlCFcwJewkm9l5oVI3Yd4BSB6hQ',
    appId: '1:130766279675:web:16b31da753c40beb5f315e',
    messagingSenderId: '130766279675',
    projectId: 'sheydoc-app',
    authDomain: 'sheydoc-app.firebaseapp.com',
    storageBucket: 'sheydoc-app.firebasestorage.app',
    measurementId: 'G-DQVVYHR1B3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCT4rJeHz3rHKeqEotr0HF2Qfpy6AVkAeI',
    appId: '1:130766279675:android:30625e8111f7eb255f315e',
    messagingSenderId: '130766279675',
    projectId: 'sheydoc-app',
    storageBucket: 'sheydoc-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiWJyUvnPsK0sv1r4c3cOZg89tbzO-4RQ',
    appId: '1:130766279675:ios:ef9669953b0c62665f315e',
    messagingSenderId: '130766279675',
    projectId: 'sheydoc-app',
    storageBucket: 'sheydoc-app.firebasestorage.app',
    iosBundleId: 'com.example.sheydocApp',
  );
}
